import mashedPotato from "./images/potato-recipes-mashed-potato-pancakes.jpeg";
import potatoEnchiladas from "./images/beef-enchiladas.jpg";
import turkeyChilli from "./images/Turkey-Chili-Smothered-Sweet-Potatoes.jpg";
import maple from "./images/Maple.jpg";
import sweetTaco from "./images/Sweet-Potato-Tacos.jpg";
export default function menuContent() {
  const divContent = document.getElementById("content");
  const h1 = document.createElement("h1");
  h1.textContent = "Menu";
  divContent.appendChild(h1);
  const divParagraph = document.createElement("div");
  const h2 = document.createElement("h2");
  h2.textContent = "Main Dishes";
  divContent.appendChild(h2);
  const divParagraph2 = divParagraph.cloneNode(false);
  const h2Main1 = h2.cloneNode(false);
  h2Main1.textContent = "PuyTato Mashed Pancakes";
  const pMain1 = document.createElement("p");
  pMain1.textContent = "Crispy, fried, and great for dipping in sour cream Mashed Potato Pancakes";
  const spanMain = document.createElement("span");
  spanMain.textContent = "8$";
  const mainImg1 = new Image();
  mainImg1.src = mashedPotato;
  divParagraph2.appendChild(h2Main1);
  divParagraph2.appendChild(pMain1);
  divParagraph2.appendChild(spanMain);
  divParagraph2.appendChild(mainImg1);
  divContent.appendChild(divParagraph2);
  const divParagraph3 = divParagraph.cloneNode(false);
  const h2Main2 = h2.cloneNode(false);
  h2Main2.textContent = "Potato Enchiladas";
  const pMain2 = pMain1.cloneNode(false);
  pMain2.textContent = "Potatoes and poblano peppers come together to make these delicious Enchiladas";
  const spanMain2 = spanMain.cloneNode(false);
  spanMain2.textContent = "4$";
  const mainImg2 = new Image();
  mainImg2.src = potatoEnchiladas;
  divParagraph3.appendChild(h2Main2);
  divParagraph3.appendChild(pMain2);
  divParagraph3.appendChild(spanMain2);
  divParagraph3.appendChild(mainImg2);
  divContent.appendChild(divParagraph3);
  const divParagraph4 = divParagraph.cloneNode(false);
  const h2Main3 = h2.cloneNode(false);
  h2Main3.textContent = "TURKEY CHILI PuyTato";
  const pMain3 = pMain1.cloneNode(false);
  pMain3.textContent = "Tender baked sweet potatoes smothered with turkey and bean chili";
  const spanMain3 = spanMain.cloneNode(false);
  spanMain3.textContent = "10$";
  const mainImg3 = new Image();
  mainImg3.src = turkeyChilli;
  divParagraph4.appendChild(h2Main3);
  divParagraph4.appendChild(pMain3);
  divParagraph4.appendChild(spanMain3);
  divParagraph4.appendChild(mainImg3);
  divContent.appendChild(divParagraph4);
  const h2SideDishes = h2.cloneNode(false);
  h2SideDishes.textContent = "Side Dishes";
  divContent.appendChild(h2SideDishes);
  const divParagraph5 = divParagraph.cloneNode(false);
  const h2Side1 = h2.cloneNode(false);
  h2Side1.textContent = "PuyTato MAPLE";
  const pSide1 = pMain1.cloneNode(false);
  pSide1.textContent = "Classic side dish that everyone will love";
  const spanSide1 = spanMain.cloneNode(false);
  spanSide1.textContent = "2$";
  const sideImg1 = new Image();
  sideImg1.src = maple;
  divParagraph5.appendChild(h2Side1);
  divParagraph5.appendChild(pSide1);
  divParagraph5.appendChild(spanSide1);
  divParagraph5.appendChild(sideImg1);
  divContent.appendChild(divParagraph5);
  const divParagraph6 = divParagraph.cloneNode(false);
  const h2Side2 = h2.cloneNode(false);
  h2Side2.textContent = "Cheesy Cauliflower";
  const pSide2 = pMain1.cloneNode(false);
  pSide2.textContent = "simple sweet potato and black bean hash, and topped with a tangy lime crema";
  const spanSide2 = spanMain.cloneNode(false);
  spanSide2.textContent = "2$";
  const sideImg2 = new Image();
  sideImg2.src = sweetTaco;
  divParagraph.classList.add("paragraph-menu");
  divParagraph2.classList.add("paragraph-menu");
  divParagraph3.classList.add("paragraph-menu");
  divParagraph4.classList.add("paragraph-menu");
  divParagraph5.classList.add("paragraph-menu");
  divParagraph6.classList.add("paragraph-menu");
  h2.classList.add("menu");
  h1.classList.add("menu");
  h2SideDishes.classList.add("side");
  divParagraph6.appendChild(h2Side2);
  divParagraph6.appendChild(pSide2);
  divParagraph6.appendChild(spanSide2);
  divParagraph6.appendChild(sideImg2);
  divContent.appendChild(divParagraph6);
}
