import mashedPotato from "./images/potato-recipes-mashed-potato-pancakes.jpeg";
import potatoEnchiladas from "./images/beef-enchiladas.jpg";
import turkeyChilli from "./images/Turkey-Chili-Smothered-Sweet-Potatoes.jpg";
export default function menuContent() {
  const divContent = document.getElementById("content");
  const h1 = document.createElement("h1");
  h1.textContent = "Menu";
  divContent.appendChild(h1);
  const divParagraph = document.createElement("div");
  const h2 = document.createElement("h2");
  h2.textContent = "Main Dishes";
  divParagraph.appendChild(h2);
  divContent.appendChild(divParagraph);
  const divParagraph2 = divParagraph.cloneNode(false);
  const h2Main1 = h2.cloneNode(false);
  h2Main1.textContent = "PuyTato Mashed Pancakes";
  const pMain1 = document.createElement("p");
  pMain1.textContent = "Crispy, fried, and great for dipping in sour cream Mashed Potato Pancakes";
  const spanMain = document.createElement("span");
  spanMain.textContent = "8$";
  const mainImg1 = new Image();
  mainImg1.src = mashedPotato;
  divParagraph2.appendChild(h2Main1);
  divParagraph2.appendChild(pMain1);
  divParagraph2.appendChild(spanMain);
  divParagraph2.appendChild(mainImg1);
  divContent.appendChild(divParagraph2);
  const divParagraph3 = divParagraph.cloneNode(false);
  const h2Main2 = h2.cloneNode(false);
  h2Main2.textContent = "Potato Enchiladas";
  const pMain2 = pMain1.cloneNode(false);
  pMain2.textContent = "Potatoes and poblano peppers come together to make these delicious Enchiladas";
  const spanMain2 = spanMain.cloneNode(false);
  spanMain2.textContent = "4$";
  const mainImg2 = new Image();
  mainImg2.src = potatoEnchiladas;
  divParagraph3.appendChild(h2Main1);
  divParagraph3.appendChild(pMain2);
  divParagraph3.appendChild(spanMain2);
  divParagraph3.appendChild(mainImg2);
  divContent.appendChild(divParagraph3);
  const divParagraph4 = divParagraph.cloneNode(false);
  const h2Main3 = h2.cloneNode(false);
  h2Main3.textContent = "TURKEY CHILI PuyTatoe";
  const pMain3 = pMain1.cloneNode(false);
  pMain3.textContent = "Tender baked sweet potatoes smothered with turkey and bean chili";
  const spanMain3 = spanMain.cloneNode(false);
  spanMain3.textContent = "10$";
  const mainImg3 = new Image();
  mainImg3.src = turkeyChilli;
  divParagraph4.appendChild(h2Main3);
  divParagraph4.appendChild(pMain3);
  divParagraph4.appendChild(spanMain3);
  divParagraph4.appendChild(mainImg3);
}
